dpl_version: 1.10.16
sudo: required
services:
  - docker
before_install:
  - docker build -t betbevn/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true betbevn/docker-react yarn test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-357595332245"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
